version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    environment:
      - FLASK_ENV=development
    restart: always
